export const Users = [
  {
    id: 1,
    profilePicture: "assets/img/person/1.jpg",
    username: "Pushkin Alex",
  },
  {
    id: 2,
    profilePicture: "assets/img/person/2.jpg",
    username: "Fet Afonasiy",
  },
  {
    id: 3,
    profilePicture: "assets/img/person/3.jpg",
    username: "Radishev Alexandr",
  },
  {
    id: 4,
    profilePicture: "assets/img/person/4.jpg",
    username: "Krylov Ivan",
  },
  {
    id: 5,
    profilePicture: "assets/img/person/5.jpg",
    username: "Karamzin Nicolay",
  },
  {
    id: 6,
    profilePicture: "assets/img/person/6.jpg",
    username: "Gogol Nikolas",
  },
  {
    id: 7,
    profilePicture: "assets/img/person/7.jpg",
    username: "Nekrasov Nikola",
  },
  {
    id: 8,
    profilePicture: "assets/img/person/8.jpg",
    username: "Lermontov Mike",
  },
  {
    id: 9,
    profilePicture: "assets/img/person/9.jpg",
    username: "Block Alex",
  },
  {
    id: 10,
    profilePicture: "assets/img/person/10.jpg",
    username: "Okudjava Bulat",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love is... nothing?",
    photo: "assets/img/posts/post-1.jpg",
    date: "5 minutes ago",
    userId: 1,
    like: 33,
    comment: 3,
  },
  {
    id: 2,
    desc: "Why I`m here?",
    photo: "assets/img/posts/post-2.jpg",
    date: "5 minutes ago",
    userId: 2,
    like: 3,
    comment: 1,
  },
  {
    id: 3,
    desc: "What is JavaScript?",
    photo: "assets/img/posts/post-3.jpg",
    date: "5 hours ago",
    userId: 3,
    like: 333,
    comment: 33,
  },
  {
    id: 4,
    desc: "Programming is...",
    photo: "assets/img/posts/post-4.jpg",
    date: "3 hours ago",
    userId: 4,
    like: 332,
    comment: 33,
  },
  {
    id: 5,
    photo: "assets/img/posts/post-5.jpg",
    date: "2 weeks ago",
    userId: 5,
    like: 353,
    comment: 35,
  },
  {
    id: 6,
    photo: "assets/img/posts/post-6.jpg",
    date: "20 minutes ago",
    userId: 6,
    like: 363,
    comment: 36,
  },
  {
    id: 7,
    desc: "Brazil",
    photo: "assets/img/posts/post-7.jpg",
    date: "15 minutes ago",
    userId: 7,
    like: 373,
    comment: 37,
  },
  {
    id: 8,
    desc: "the world is...",
    photo: "assets/img/posts/post-8.jpg",
    date: "50 minutes ago",
    userId: 8,
    like: 383,
    comment: 38,
  },
  {
    id: 9,
    photo: "assets/img/posts/post-9.jpg",
    date: "1 day ago",
    userId: 9,
    like: 339,
    comment: 39,
  },
  {
    id: 10,
    desc: "Every moment is a fresh begining",
    photo: "assets/img/posts/post-10.jpg",
    date: "5 minutes ago",
    userId: 10,
    like: 330,
    comment: 30,
  },
];
